In [1]:
import numpy as np

In [2]:
platinum = 120000
gold = 80000
silver = 50000

contador_platinum = 0
contador_gold = 0
contador_silver = 0

asientos_disponibles =np.array ([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20],[21,22,23,24,25,26,27,28,29,30],[31,32,33,34,35,36,37,38,39,40],[41,42,43,44,45,46,47,48,49,50],[51,52,53,54,55,56,57,58,59,60],[61,62,63,64,65,66,67,68,69,70],[71,72,73,74,75,76,77,78,79,80],[81,82,83,84,85,86,87,88,89,90],[91,92,93,94,95,96,97,98,99,100]],dtype = object)
asientos_reservados = []
asistentes = []


In [14]:
def comprar_entradas():
  global contador_platinum,contador_gold,contador_silver,asientos_disponibles,asientos_reservados,asistentes
  print('-----Valor entradas-----')
  print('platinum  $120.000 (asientos del 1 al 20)')
  print('Gold $80.000 (asientos del 21 al 50)')
  print('Silver $50.000 (asientos de 51 al 100)')
  while True:
    cantidad_asientos = int(input('ingrese la cantidad de asientos que desea comprar (de 1 a 3): '))
    if cantidad_asientos >= 1 and cantidad_asientos <= 3:
      break
    else:
      print('debe ingresar un valor entre 1 y 3')
  print(f'los asientos disponibles son: ')
  print(asientos_disponibles)
  print('-'*50)
  i = 0
  for i in range(cantidad_asientos):
    asiento = int(input(f'ingrese el asiento N°{i+1} que desea comprar: '))
    if asiento >=1 and asiento <=20:
      contador_platinum += 1
      np.delete(asientos_disponibles, asiento - 1,)
      asientos_reservados.append(asiento)
      i += 1

    elif asiento >=21 and asiento <=50:
      contador_gold += 1
      np.delete(asientos_disponibles, asiento - 1,)
      asientos_reservados.append(asiento)
      i += 1

    elif asiento >=51 and asiento <=100:
      contador_silver += 1
      np.delete(asientos_disponibles, asiento - 1,)
      asientos_reservados.append(asiento)
      i += 1
  try:
    while True:
      rut = int(input('Ingrese su rut (sin puntos, ni digito verfificador): '))
      if len(str(rut)) == 8:
        break
      else:
        print('debe ingresar solo 8 caracteres')
    asistentes.append(rut)
    print('operaciones realizada correctamente')
  except:
    print('solo debe ingresar numeros')

In [4]:
def mostrar_ubicaciones_disponibles():
  global asientos_disponibles
  print('*'*30)
  print('ubicaciones disponibles')
  print(asientos_disponibles)

In [5]:
def listado_asistentes():
  global lista_asistentes
  print('*'*30)
  print('asistentes')
  print(asistentes)

In [6]:
def ganancias_totales():
  global contador_platinum,contador_gold,contador_silver,platinum,gold,silver
  total_platinum = 120000 * contador_platinum
  total_gold = 80000 * contador_gold
  total_silver = 50000 * contador_silver
  print(f'platinum ${platinum}, cantidad = {contador_platinum}, total = {total_platinum}')
  print(f'gold ${gold}, cantidad = {contador_gold}, total = {total_gold}')
  print(f'silver ${silver}, cantidad = {contador_silver}, total = {total_silver}')

In [7]:
def salir():
  print('gracias por preferir creativos.cl')
  print('Cristobal Bustamante')
  print('11/07/2023')

In [9]:
def menu():

  while True:
    try:
      print('------ Menu ------')
      print('1. comprar entradas')
      print('2. mostrar ubicaciones disponibles')
      print('3. mostrar asisitentes')
      print('4. mostrar ganancias totales')
      print('5. salir')


      opcion = int(input('Seleccione una opcion: '))

      if opcion == 1:
        comprar_entradas()
      elif opcion == 2:
        mostrar_ubicaciones_disponibles()
      elif opcion == 3:
        listado_asistentes()
      elif opcion == 4:
        ganancias_totales()
      elif opcion == 5:
        salir()
        break
      else:
        print('Opcion invalida, vuelva a seleccionar')
        print(50*'*')
    except ValueError:
      print('error ----> debe ingresar solo numeros')
      print(50 * '*')

In [15]:
try:
  menu()
except KeyboardInterrupt:
  print('usted a interruptido el programa manualmente')

------ Menu ------
1. comprar entradas
2. mostrar ubicaciones disponibles
3. mostrar asisitentes
4. mostrar ganancias totales
5. salir
Seleccione una opcion: 1
-----Valor entradas-----
platinum  $120.000 (asientos del 1 al 20)
Gold $80.000 (asientos del 21 al 50)
Silver $50.000 (asientos de 51 al 100)
ingrese la cantidad de asientos que desea comprar (de 1 a 3): 1
los asientos disponibles son: 
[[1 2 3 4 5 6 7 8 9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]
 [61 62 63 64 65 66 67 68 69 70]
 [71 72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89 90]
 [91 92 93 94 95 96 97 98 99 100]]
--------------------------------------------------
ingrese el asiento N°1 que desea comprar: 1
Ingrese su rut (sin puntos, ni digito verfificador): 20379176
operaciones realizada correctamente
------ Menu ------
1. comprar entradas
2. mostrar ubicaciones disponibles
3. mostrar a